name: rework-from-jenkins

on:
    workflow_dispatch:
      inputs:
        OS:
        description: 'Pick OS'
        required: true
        default: 'linux'
        type: choice
        options:
          - linux
          - darwin
          - windows
          - all
        ARCH:
          description: 'Pick ARCH (amd64, aarch64)'
          required: true
          default: 'amd64'

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Building
              run: |
                echo 'Build...'
                echo 'Build for platform: ${{ github.event.inputs.OS }}'
                echo 'Build for arch: ${{ github.event.inputs.ARCH }}'
