name: rework-from-jenkins

on: push

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run test
              run: echo 'Runs some tests'